### ISSUE TITLE
Visualize toppling effect in mechanics

### ISSUE THREAD

**Issue by himanshub16** [himanshub16/cool-physics#2]
Place some blocks on the canvas and allow to choose a point on the block where the force will be applied.

Allow to adjust factors like `coefficient of friction`, `force applied`, etc. and show if the object would topple at some point.

**Comment by falconis** [comment]
I would like to work on this..

**Comment by himanshub16** [comment]
Just describe a brief outline of how you'll be doing it before starting. Sketches/drawings would be helpful in understanding.

**Comment by falconis** [comment]
Sure! I'll start tonight.

**Comment by falconis** [comment]
![toppling](https://user-images.githubusercontent.com/30634978/34909062-b220bc28-f8c0-11e7-9674-a34d864f6bdb.jpg)
This is a rough diagram I made.
I have a basic understanding of the concept, still I am using [this](url) website as a reference.


Currently I am learning canvas. I'll hopefully complete the project by tomorrow night.

**Comment by falconis** [comment]
I completed the toppling animation. I'll complete the issue today.

**Comment by himanshub16** [comment]
Sure. Make it available on your fork via GitHub pages.

**Comment by falconis** [comment]
Sir how do I do that?Since there are 3 index.html files
