### ISSUE TITLE
Visualize 2D-projectile motion with the help of a catapult

### ISSUE THREAD

**Issue by himanshub16** [himanshub16/cool-physics#3]
The interface would allow controlling the parameters like `initial_velocity`, `acceleration due to gravity`, `angle of projection`, and the project the object as per the measurements.

> Similar to Angry birds, but with tunables and visible metrics to understand physics behind it.

**Comment by arpitmisraw** [comment]
I would like to work on this.

**Comment by arpitmisraw** [comment]
It took me some time to learn about canvas and analyze you code. I've made modifications to involve angle of projection. There are some minor bugs. Is it okay if I take another day?

**Comment by arpitmisraw** [comment]
@himanshub16
